# Generated by Django 5.2 on 2025-04-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slidergallery',
            name='image',
            field=models.ImageField(max_length=500, upload_to='resume_gallery/'),
        ),
    ]
